[ONU]
# IP address of your TP-Link ONU
IP = 192.168.1.1
# Username (typically "user" or "admin")
USERNAME = user
# Web UI Password
PASSWORD = YOUR_ROUTER_PASSWORD

[MQTT]
ENABLE = False
BROKER = 127.0.0.1
PORT = 1883
USER = YOUR_MQTT_USER
PASSWORD = YOUR_MQTT_PASSWORD
TOPIC = tele/onu/gpon_stats
CLIENT_ID = onu_monitor

[INFLUXDB]
ENABLE = False
URL = http://127.0.0.1:8086
TOKEN = YOUR_INFLUX_TOKEN
ORG = YOUR_ORG
BUCKET = network_stats
